@startuml
class ApplicationUser {
    + ApplicationUser()
    + ApplicationUser(id:string, name:string, surname:string, userName:string)
    + ApplicationUser(id:string, name:string, surname:string, userName:string, birthDate:DateOnly, age:int, gender:Gender)
    + Name : string? <<get>> <<set>>
    + Surname : string? <<get>> <<set>>
    + BirthDate : DateOnly <<get>> <<set>>
    + Age : int <<get>> <<set>>
    + Gender : Gender <<get>> <<set>>
}
IdentityUser <|-- ApplicationUser
ApplicationUser o-- "0..*" Team : "CaptainOf"
ApplicationUser o-- "0..*" TeamInvitation : "TeamInvitations"
ApplicationUser o-- "0..*" InterestedIn : "Interested"
@enduml
