@startuml
hide methods
class ApplicationUser {
    + Name : string? <<get>> <<set>>
    + Surname : string? <<get>> <<set>>
    + BirthDate : DateOnly <<get>> <<set>>
    + Age : int <<get>> <<set>>
    + Gender : Gender <<get>> <<set>>
}
@enduml