@startuml
!include .\\ApplicationUser.puml
!include .\\Gender.puml
!include .\\InterestedIn.puml
!include .\\Item.puml
!include .\\Purchase.puml
!include .\\PurchaseStatus.puml
!include .\\Sport.puml
!include .\\Team.puml
!include .\\TeamInvitation.puml
@enduml
