@startuml
!include ./ApplicationUser.puml
!include ./Game.puml
!include ./GameInvitation.puml
!include ./Gender.puml
!include ./InterestedIn.puml
!include ./Item.puml
!include ./Purchase.puml
!include ./PurchaseItem.puml
!include ./PurchaseStatus.puml
!include ./RefereeGroup.puml
!include ./Sport.puml
!include ./Team.puml
!include ./TeamInvitation.puml
@enduml
