@startuml
class InterestedIn {
    + InterestedIn()
    + InterestedIn(userId:string, sportId:int, skill:int)
    + UserId : string <<get>> <<set>> = "0"
    + SportId : int <<get>> <<set>>
    + Skill : int <<get>> <<set>>
}
InterestedIn o-> "UserInterested" ApplicationUser
InterestedIn o-> "Sport" Sport
@enduml
