@startuml
class RefereeGroup {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + Rules : string? <<get>> <<set>>
    + GameId : int <<get>> <<set>>
}
@enduml
