@startuml Sport
class Sport {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + MinimumNumberOfPlayers : int <<get>> <<set>>
    + NumberOfReferees : int <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + BasicRules : string <<get>> <<set>>
}
@enduml
