@startuml
class TeamInvitation {
    + TeamInvitation()
    + TeamInvitation(userId:string, teamId:int, message:string)
    + UserId : string <<get>> <<set>>
    + TeamId : int <<get>> <<set>>
    + InvitationMessage : string <<get>> <<set>> = "Invitation Message for a team member"
    + InvitationAccepted : bool <<get>> <<set>> = false
}
TeamInvitation o-> "User" ApplicationUser
TeamInvitation o-> "Team" Team
@enduml
