@startuml
class Team {
    + Team()
    + Team(name:string, maxMembers:int, minAge:int, maxAge:int, captain:ApplicationUser, sport:Sport, description:string?)
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + MaxMembers : int <<get>> <<set>>
    + MinAge : int <<get>> <<set>> = 3
    + MaxAge : int <<get>> <<set>> = 3
}
@enduml
